### PR TITLE
Fix kernel module build on Linux >=5.1

### PR DESCRIPTION
**Pull request by salut-c-leo**
I have zero knowledge about Linux kernel development, but I guess it works now on 5.1, since `darling shell` is able to load the module on my PC. I defined `MAP_PRIVATE`, as the compiler said it was never declared before, and I have no idea if it's how it should be declared.

### CODE REVIEW

File: darling/traps.c [hunk 1]
```diff
@@ -385,7 +385,7 @@ static void darling_ipc_inherit(task_t old_task, task_t new_task)
 
 // No vma from 4.11
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 0)
-static int mach_mmap_fault(struct vm_fault *vmf)
+static unsigned int mach_mmap_fault(struct vm_fault *vmf)
```
Comment (bugaevc) [inline darling/traps.c]: No, this would break on Linux < 5.1

As I've said, it's better to use `vm_fault_t` itself, 'cause it'll always be of the right type.

File: darling/binfmt_loader.c [hunk 2]
```diff
@@ -32,6 +32,7 @@
 #   define MACH_HEADER_STRUCT mach_header_64
 #   define SECTION_STRUCT section_64
 #	define MAP_EXTRA 0
+#	define MAP_PRIVATE 0
```
Comment (bugaevc) [inline darling/binfmt_loader.c]: *I think* the right way to fix this is to `#include <linux/mman.h>` (in addition to `<linux/mm.h>` and `<asm/mman.h>` that are already present) at the top of `binfmt.c`

**Review by bugaevc — COMMENTED** [review]
(So apparently GitHub has this review thing where it doesn't display my comments — by does display them to _me_ — until I open a non-mobile version of the page a tap "submit review". Great UX! 👍)

File: darling/traps.c (hunk 1 above)
Comment (salut-c-leo) [reply darling/traps.c]: I have no idea on how I should do this, since I have zero knowledge on Linux kernel development.

Comment (bugaevc) [reply darling/traps.c]: Just make it say `static vm_fault_t mach_mmap_fault(...`

**Comment by salut-c-leo** [comment]
It should be correct now.

**Comment by jamesbrink** [comment]
Tested on Arch linux 5.1.3, works for me now. thanks @mrtino !

**Comment by jamesbrink** [comment]
@mrtino I have included your patch in https://aur.archlinux.org/pkgbase/darling-git/
Thanks again!

**Comment by ahyattdev** [comment]
@bugaevc not sure how to test this on < 5.1, any recommendations?

**Comment by bugaevc** [comment]
Mmm, what do you mean? Just try to build this for a < 5.1 kernel and see if it builds/works.

**Comment by ahyattdev** [comment]
This PR doesn't compile on Ubuntu 18.04 with kernel 4.15.0-50-generic.

```
/home/andrewhyatt/darling/src/lkm/darling/traps.c:388:8: error: unknown type name ‘vm_fault_t’
 static vm_fault_t mach_mmap_fault(struct vm_fault *vmf)
        ^~~~~~~~~~
```

**Comment by jamesbrink** [comment]
I think the issue is likely just the macro, 
`#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 0)`
I think this needs to be something like 

`#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 1, 0)`, not sure why **4.11.0** was chosen as it i seems to have broken at **5.1**

I don't really have a good development environment in place right to to test this

**Comment by jamesbrink** [comment]
I think we just needed the additional `elif` statement in the macro, @ahyattdev can you confirm that PR #6 now builds on your machine?

**Comment by ahyattdev** [comment]
I will test it

**Comment by ahyattdev** [comment]
@jamesbrink that builds successfully.
